### ISSUE TITLE
.size() not a function error in jsm script

### ISSUE THREAD

**Issue by PJTewkesbury** [lcourson/Hangfire.Dashboard.Management.v2#15]
Hi,
I am using your nuget package in my project, and it sees the custom jobs and displays them correctly, but when I select a job and click on 'Execute' from the management page, it does nothing. Also I cannot change the selection of the 'Task Type' 

Chrome reports the following error in jsm

```
Uncaught TypeError: i.element.find(...).size is not a function
    at k (jsm:5)
    at new d (jsm:5)
    at HTMLDivElement.<anonymous> (jsm:5)
    at Function.each (js17270:2)
    at S.fn.init.each (js17270:2)
    at S.fn.init.a.fn.datetimepicker (jsm:5)
    at HTMLDivElement.<anonymous> (jsm:25)
    at Function.each (js17270:2)
    at S.fn.init.each (js17270:2)
    at Management.hangfire.Management.Management._initialize (jsm:24)
```

If I replace the .size() for .length in bootstrap-datetimepicker.min.js it all works correctly.

Thanks

**Comment by lcourson** [comment]
This should be fixed in the latest package (v2.2.0).

**Comment by vhafdal** [comment]
Hi,
I just upgraded to 2.2.0 an wanted to test how the management would work.
I get the same error and no job is run aka nothing happens
![image](https://user-images.githubusercontent.com/5278320/171644227-bff68392-efd6-4960-8dcb-7e6a5eb8fce5.png)

I have updated Hangfire to  1.7.29

Have you been able to reproduce the issue and will a updated Nuget package be available in the near future ?

Best Regards,
Valdi Hafdal

**Comment by lcourson** [comment]
Sorry for the delay.  The latest package (2.3.0) has replaced the bootstrap-datetimepicker with a new library that should work.  Please give it a try and let me know if this resolves your issue.
