### ISSUE TITLE
Package metadata

### ISSUE THREAD

**Issue by agust220** [lcourson/Hangfire.Dashboard.Management.v2#20]
Hey guys,
I just thought it might be a good idea to add some metadata to your NuGet package such as package description, repository url, etc. 
It doesn't seem as legit compared to other packages in the NuGet Package Manager because of this.
I'm using the package in a project but I had to google it to find the github repository for setup etc.

![image](https://user-images.githubusercontent.com/9974682/181738268-2e71f5a2-c995-4e1d-90e4-d99f522c474d.png)

**Comment by lcourson** [comment]
Thanks for the heads up.  The information has been filled out in the latest package.
