### ISSUE TITLE
Scheduling a job from Dashboard is not working

### ISSUE THREAD

**Issue by pchalaris-singularlogic** [lcourson/Hangfire.Dashboard.Management.v2#27]
Hello and thanks for the great work. I am using the Dashboard and when I schedule a job from UI, even though the message shows success, the scheduled job is not created and the "view job" link is undefined. Is there a way for me to fix it ? Thanks!
![Capture](https://github.com/lcourson/Hangfire.Dashboard.Management.v2/assets/81621721/7c3622db-f0e2-4de2-be02-847a5fc3c670)

**Comment by pchalaris-singularlogic** [comment]
Seems to be language-related issue. I used greek on [DisplayName("..")] and when switched back to english the issue is gone.

**Comment by lcourson** [comment]
This is caused by the route to schedule the job using the DisplayName's value.  I have changed this to use the MethodName for the route and only use the DisplayName for the UI.  The next release of 2.3.2 should have this fix in place.

**Comment by lcourson** [comment]
This is caused by the route to schedule the job using the DisplayName's value. I have changed this to use the MethodName for the route and only use the DisplayName for the UI. The next release of 2.3.2 should have this fix in place.
