### ISSUE TITLE
Remove non interface restriction in GetAllJobs()

### ISSUE THREAD

**Issue by devbrains-com** [lcourson/Hangfire.Dashboard.Management.v2#5]
Hey Guys, I tried to use your hangfire extension and it works nice, but there is one thing I need to change. In the GetAllJobs() method on line 19, there is a check if the type is not an interface. Because we would have a simple contracts nuget per job, containing the attributed interface for a job, we need to remove that restriction.

I already tested that based on the master and it works as expected. Tried to push something to a branch and create a PR, but I have no rights.

Before:
foreach (Type ti in assembly.GetTypes().Where(x => **!x.IsInterface &&** typeof(IJob).IsAssignableFrom(x) && x.Name != (typeof(IJob).Name))) {

After:
foreach (Type ti in assembly.GetTypes().Where(x => typeof(IJob).IsAssignableFrom(x) && x.Name != (typeof(IJob).Name))) {

Could you please change that and create a new release?

That would be awesome.. :)

Thank you
Michael

**Comment by devbrains-com** [comment]
Example of usage:  

`
    [ManagementPage("Vendor classification", "Vendor classification")]
    public interface IVendorClassificationJobs : IJob
    {
        [DisplayName("Reference vendor classification")]
        [Description("Processes different reference vendor sources")]
        [Queue("vendorclassification")]
        Task<string> ProcessVendorsAsync(VendorDataSource source, string runId, int? limit, PerformContext context);
    }
`

**Comment by lcourson** [comment]
This restriction has been removed in the latest version 2.1.0
