### ISSUE TITLE
Issue on creation of Cron Job 

### ISSUE THREAD

**Issue by pdeki** [lcourson/Hangfire.Dashboard.Management.v2#7]
When I try to create the Cron job on OSX error is:

Error! The time zone ID 'Eastern Standard Time' was not found on the local computer

Do you know what could be the root cause ? I found one year old issue on Dashboard: https://github.com/HangfireIO/Hangfire/issues/1407 

Tnx

**Comment by keymakerpl** [comment]
Unfornetly TimeZone is hardcoded. ManagementBasePage.cs line:122.

**Comment by pdeki** [comment]
I created the fix (it works for me). If you allow me I can make a push to the new branch and request PR.

**Comment by lcourson** [comment]
Sorry about this issue... It has been fixed in the latest build
