### ISSUE TITLE
Shedule the same job multiple times with different parameters

### ISSUE THREAD

**Issue by timdhaeyer** [lcourson/Hangfire.Dashboard.Management.v2#9]
Hi,

Is it possible to shedule the same job multiple times with different parameters? That way I don't need to write specific methods for all the different jobs I want.
Now I see that the job name for the recurring job is quite fixed, but maybe I'm missing something.

Kind Regards
Tim

**Comment by carlittos** [comment]
Hi @timdhaeyer 
I was surprised when I tried to create my second recurring job. I did not expect this limitation and I see you have a branch with a possible solution.
Hopefully, @lcourson will let us know when this can be adjusted since this is such a great extension and makes our lives much easier when it comes to creating generic jobs.

**Comment by Mohamed-Effat** [comment]
For anyone who come across this issue, the feature is now supported thanks to @timdhaeyer 
The feature usage is not specified in the readme but here is how it's used:

It is used by specifying the `[AllowMultiple]` attribute over your job function
example:
```
    [ManagementPage(MenuName = "Jobs", Title = "Jobs")]
    public class JobsService : IJob
    {

        [AllowMultiple]
        [DisplayName("MyJob")]
        [Description("This is a job that allows multiple recurring scheduling based on the provided unique name.")]
        public void MyJob(PerformContext context)
        {

        }
    }
```

Then in the management tab when choosing task type recurring you will now see a Job Name field to enter a **_unique_** name for that job that will be used as a the unique identifier for that recurring job and thus allowing to have multiple recurring jobs of the same job even if the job parameters were not changed

![image](https://user-images.githubusercontent.com/27577484/163720872-f5e38213-6e21-4ef6-94eb-1a71848a5f86.png)
